/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package something;

import org.riversun.slacklet.Slacklet;
import org.riversun.slacklet.SlackletRequest;
import org.riversun.slacklet.SlackletResponse;
import org.riversun.slacklet.SlackletService;
import org.riversun.xternal.simpleslackapi.SlackChannel;

import java.io.IOException;

public class App {
    public static void main(String[] args) {
        String botToken ="xoxb-854564613383-853322617664-IqwPL7VwLOPF4NKzcTYfHlIB" ;

        SlackletService slackService = new SlackletService(botToken);

        // slackletを追加する
        slackService.addSlacklet(new Slacklet() {

            @Override
            public void onMessagePosted(SlackletRequest req, SlackletResponse resp) {
                System.out.println("receive");
                // メッセージがユーザーからポストされた

                // メッセージがポストされたチャンネルを取得する
                SlackChannel channel = req.getChannel();
                System.out.println(channel.getName());
                String content = req.getContent();
                if(content.trim().equals("CICD")){
                    // メッセージがポストされたチャンネルに対して、BOTからメッセージを送る
                    resp.reply("実践入門！");
                }
            }
        });

        // slackletserviceを開始(slackに接続)
        System.out.println("starting");
        try {
            slackService.start();
        } catch (IOException e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
        System.out.println("started");
    }
}
